config: base.yaml

# 尝试逐步把SWA替换成identity
expid: cpt-contswa

ckpt_dir: /home/ma-user/work/bucket-wulan-green/zhaoyusheng/checkpoints/Qwen/Qwen3-0.6B-Base/

global_batch_size: 1024
micro_batch_size: 2
max_steps: 2000
warmup_steps: 0
learning_rate: 5e-5
min_lr: 5e-5
weight_decay: 0.1
num_devices: 8

data_dir: "/home/ma-user/work/bucket-wulan-green/zhaoyusheng/fineweb-edu/sample/10BT/"
num_workers: 16
save_ckpt: true
save_path: /home/ma-user/work/bucket-wulan-green/${MY_REAL_NAME-default}/ckpt/qwen0.6b-4k-cpt-contswa

enable_tensorboard: true
tensorboard_root: /home/ma-user/work/bucket-wulan-green/${MY_REAL_NAME-default}/tb

use_research: true
research_swa_size: 1024
research_swa_layers_str: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27"
research_separate_parameter: true
research_breakpoint_schedule_stable: -1

research_remove_order_str: "15,13,17,11,19,9,21,7,23,5"
research_remove_interval: 100
