# Quick debug / convergence test config
config: base.yaml

expid: debug

global_batch_size: 128
micro_batch_size: 2
max_steps: 300
num_devices: 4
warmup_steps: 5
learning_rate: 5e-5
min_lr: 5e-5
weight_decay: 0.1

dataset_name: "debug"
dataset_dir: "data"
num_workers: 16
save_ckpt: false

enable_tensorboard: false

log_kv_B: 128
